### ISSUE TITLE
Mafia WBK MKO PABLOS Dawner 

### ISSUE THREAD

**Issue by pablosdaw** [Unity-Technologies/com.unity.services.samples.use-cases#19]
![Screenshot_2023-12-27-05-08-22-01_abd967db7ec4f4f4e08e4c6789a62f6a.jpg](https://github.com/Unity-Technologies/com.unity.services.samples.use-cases/assets/26622978/fcdef898-d228-4612-8705-13de0fceb1f0)

**Comment by Eric-Robitaille** [comment]
Spam
