### ISSUE TITLE
Claim Battle Pass Tier doesn't work

### ISSUE THREAD

**Issue by Leguna** [Unity-Technologies/com.unity.services.samples.use-cases#6]
Battle pass tier claimed, but the reward doesn't. Setup UGS based on readme.md

https://github.com/Unity-Technologies/com.unity.services.samples.use-cases/blob/42f2e87ec22baf50dc42ce3869a209be29229c2c/Assets/Use%20Case%20Samples/Battle%20Pass/Cloud%20Code/BattlePass_ClaimTier.js#L203-L215

**Comment by husaynhasan10-creator** [comment]
[BallController.cs](https://github.com/user-attachments/files/31116173/BallController.cs)
[FootballBallController.cs](https://github.com/user-attachments/files/31116165/FootballBallController.cs)
[FootballPlayerController.cs](https://github.com/user-attachments/files/31116170/FootballPlayerController.cs)
[MainMenuManager.cs](https://github.com/user-attachments/files/31116171/MainMenuManager.cs)
[MatchInput.cs](https://github.com/user-attachments/files/31116174/MatchInput.cs)
[MatchManager.cs](https://github.com/user-attachments/files/31116166/MatchManager.cs)
[MobileJoystick.cs](https://github.com/user-attachments/files/31116172/MobileJoystick.cs)
[PlayerController.cs](https://github.com/user-attachments/files/31116164/PlayerController.cs)
[PrototypeGameBuilder.cs](https://github.com/user-attachments/files/31116168/PrototypeGameBuilder.cs)
[README.md](https://github.com/user-attachments/files/31116169/README.md)
[TeamSelectionManager.cs](https://github.com/user-attachments/files/31116167/TeamSelectionManager.cs)
